/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // PacaPOS v2 — paleta plana rosa/vino (mockup redesign)
        primary: '#D6337F',
        'primary-deep': '#B92B6C',
        'primary-container': '#B92B6C',
        'on-primary': '#FFFFFF',
        'primary-fixed': '#FBE1EF',
        'primary-fixed-dim': '#F4CBE2',
        'on-primary-fixed': '#33132A',
        'on-primary-fixed-variant': '#B92B6C',
        surface: '#FBF4F8',
        'surface-bright': '#FBF4F8',
        'surface-dim': '#F4E9EF',
        'on-surface': '#33132A',
        'on-surface-variant': '#93707F',
        'on-background': '#33132A',
        'surface-tint': '#D6337F',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FDF7FA',
        'surface-container': '#F7E8F0',
        'surface-container-high': '#F1DCE7',
        'surface-container-highest': '#F5DFEB',
        'surface-variant': '#F6E4EE',
        outline: '#F1DCE7',
        'outline-variant': '#F4CBE2',
        secondary: '#D6337F',
        'secondary-container': '#FBE1EF',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#B92B6C',
        'secondary-fixed': '#FBE1EF',
        'secondary-fixed-dim': '#F4CBE2',
        'on-secondary-fixed': '#33132A',
        'on-secondary-fixed-variant': '#B92B6C',
        tertiary: '#B92B6C',
        'tertiary-container': '#F1DCE7',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#33132A',
        'tertiary-fixed': '#FBE1EF',
        'tertiary-fixed-dim': '#F4CBE2',
        'on-tertiary-fixed': '#33132A',
        'on-tertiary-fixed-variant': '#B92B6C',
        'inverse-surface': '#2C0E1F',
        'inverse-on-surface': '#F6CFE4',
        'inverse-primary': '#F9CBE2',
        error: '#C2185B',
        'error-container': '#FBE1EF',
        'on-error': '#FFFFFF',
        'on-error-container': '#B92B6C',
        background: '#FBF4F8',
        'mint-surface': '#FBE1EF',
        'mint-badge': '#F4CBE2',
        'surface-canvas': '#FBF4F8',
        'surface-card': '#FFFFFF',
        'live-violet': '#6D28D9',
        'live-pulse': '#F43F5E',
        'flash-amber': '#F59E0B',
        'tertiary-fixed': '#EDE9FE',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.625rem',
        xl: '0.75rem',
        '2xl': '0.875rem',
        '3xl': '1rem',
        full: '9999px',
      },
      // Acabado plano: sin sombras (diseño v2)
      boxShadow: {
        DEFAULT: '0 0 #0000',
        sm: '0 0 #0000',
        md: '0 0 #0000',
        lg: '0 0 #0000',
        xl: '0 0 #0000',
        '2xl': '0 0 #0000',
        inner: 'inset 0 1px 2px 0 rgb(51 19 42 / 0.04)',
      },
      spacing: {
        'space-xs': '0.5rem',
        'space-md': '1rem',
        'margin-mobile': '1rem',
        'space-xxs': '0.25rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.75rem',
        'space-pos-hit': '3.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-lg': '1.25rem',
      },
      fontFamily: {
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-pos-mobile': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-pos': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-numeric': ['Space Grotesk', 'sans-serif'],
        'label-badge': ['Plus Jakarta Sans', 'sans-serif'],
        // Landing (plantilla v3)
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        caption: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-pos-mobile': ['26px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-pos': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-numeric': ['15px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        // Landing (plantilla v3)
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11.5px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '600' }],
        'label-lg': ['15px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        caption: ['11px', { lineHeight: '14px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
